In [2]:
import numpy as np

### арифтметичні операції над Нампай масивами

In [28]:
rm = np.random.randint(0, 10, size=(3,3))
im = np.identity(3)

print(f"""
Початкова рандомна матриця: 
{rm}
Початкова матриця ідентичності: 
{im}
Арифметичні операції які здйснюються поелементно:
Додавання
{rm + im + 1} 
Віднімання
{rm - im + 5}
Множення і решта операцій (складні вирази)
{(rm - 5) * (im + 5) }


{rm[rm >= 5]}
""")


Початкова рандомна матриця: 
[[6 4 1]
 [3 7 8]
 [7 4 2]]
Початкова матриця ідентичності: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Арифметичні операції які здйснюються поелементно:
Додавання
[[8. 5. 2.]
 [4. 9. 9.]
 [8. 5. 4.]] 
Віднімання
[[10.  9.  6.]
 [ 8. 11. 13.]
 [12.  9.  6.]]
Множення і решта операцій (складні вирази)
[[  6.  -5. -20.]
 [-10.  12.  15.]
 [ 10.  -5. -18.]]


[6 7 8 7]



### трохи про вищу математику

In [ ]:
# навіть якщо ми не знаємо як рахувати детернінант матриці, Пайтон знає
np.linalg.det(rm)

np.float64(55.000000000000014)

In [34]:
RM = np.matrix(rm)

RM

matrix([[6, 4, 1],
        [3, 7, 8],
        [7, 4, 2]])

In [37]:
A = np.array([ [1, 2, 3], [2, 2, 2], [3, 3, 3] ])
B = np.array([ [3, 2, 1], [1, 2, 3], [-1, -2, -3] ])
print(f"Маємо два масиви:\n {A} \n {B}")

R = A * B
print(f"Тут виконується поелементне множення:\n {R}")

R = np.dot(A, B)
print(f"Тут, масиви перемножуються як матриці:\n {R}")

MA = np.matrix(A)
MB = np.matrix(B)

print(f"""Тут масиви перетворені на матриці і далі перемножуються:\n 
{MA * MB} 
Так само  як і:
{MA.dot(MB)}
""")

Маємо два масиви:
 [[1 2 3]
 [2 2 2]
 [3 3 3]] 
 [[ 3  2  1]
 [ 1  2  3]
 [-1 -2 -3]]
Тут виконується поелементне множення:
 [[ 3  4  3]
 [ 2  4  6]
 [-3 -6 -9]]
Тут, масиви перемножуються як матриці:
 [[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]
Тут масиви перетворені на матриці і далі перемножуються:
 
[[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]] 
Так само  як і:
[[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]



### Пробуємо вирівнювати масиви

In [47]:
print(rm.shape, rm)

a1 = np.array([1, 2, 3])
print(a1.shape, a1)

rm + a1

a2 = np.array([ [1], [2], [3] ])
print(a2.shape, a2)

rm + a2

A2 = a2[np.newaxis, :]
print(A2.shape)

rm + A2

(3, 3) [[6 4 1]
 [3 7 8]
 [7 4 2]]
(3,) [1 2 3]
(3, 1) [[1]
 [2]
 [3]]
(1, 3, 1)


array([[[ 7,  5,  2],
        [ 5,  9, 10],
        [10,  7,  5]]])